import MainLayout from "./_components/layout/MainLayout";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <>
      <MainLayout>{children}</MainLayout>
    </>
  );
}
